import type {Card} from '../../types';
import {
    analyzeImportedCards,
    assertNoImportErrors,
    normalizeImportedCard,
    type ImportedCard,
} from '../importValidator';

type RawCard = ImportedCard;


//caocao


export const caoCaoCards: RawCard[] = [
    // This is the starting deck which is 4 cards of each attack and defend + 1 skill card
  {
    id: 'caocao_strike',
    name: 'Wei Strike',
    type: 'ATTACK',
    cost: 1,
    target: 'ENEMY',
    value: 6,
    rarity: 'basic',
    effects: [{ type: 'damage', value: 6, target: 'ENEMY' }],
  },
	{
		id: 'caocao_defend',
		name: 'Wei Defend',
		type: 'SKILL',
		cost: 1,
		target: 'SELF',
		value: 5,
		rarity: 'basic',
		effects: [{ type: 'block', value: 5, target: 'SELF' }],
	},
	{
		id: 'caocao_influence',
		name: 'Gather Influence',
		type: 'SKILL',
		cost: 0;
		target: 'SELF',
		rarity: 'basic',
		effects: [{ type: 'draw', value: 2, target: 'SELF' }],
	},
	{
		id: 'caocao_command_decree',
		name: 'Command Decree',
		type: 'ATTACK',
		cost: 0,
		target: 'ENEMY',
		value: 3,
		rarity: 'basic',
		effects: [
			{type: 'damage', value: 3, target: 'ENEMY'},
			{type: 'apply_status', value: 1, target: 'SELF', statusId: 'command'},
		],
		fleeting: true,
	},
	{
		id: 'caocao_retreat',
		name: 'Tactical Retreat',
		type: 'skill',
		cost: 0,
		target: 'SELF',
		rarity: 'basic',
		effects: [
			{type: 'block', value: 4, target: 'SELF'},
			{type: 'draw', value: 1, target: 'SELF'},
		],
	},

	//Common
	{
		id: 'caocao_sweep_plains',
		name: 'Sweep the Plains',
		type: 'ATTACK',
		cost: 2,
		target: 'ALL_ENEMIES',
		value: 4,
		rarity: 'common',
		effects: [
      {type: 'damage', value: 4, target: 'ALL_ENEMIES'},
      {type: 'apply_status', value: 1, target: 'ALL_ENEMIES', statusId: 'panic'},
    ],
	},
	
	{
		id: 'caocao_ambush',
		name: 'Ambush',
		type: 'SKILL',
		cost: 1,
		target: 'ENEMY',
		value: 5,
		rarity: 'common',
		effects: [
			{type: 'damage', value: 5, target: 'ENEMY'},
			{type: 'block', value: 3, target: 'SELF'},
		],
	},
	{
		id: 'caocao_fortify',
		name: 'Fortify',
		type: 'SKILL',
		cost: 2,
		target: 'SELF',
		value: 10,
		rarity: 'common',
    effects: [
      { type: 'block', value: 10, target: 'SELF' },
      { type: 'apply_status', value: 2, target: 'SELF', statusId: 'formation' },
    ],
	},
	{
		id: 'caocao_suppress',
		name: 'Suppress',
		type: 'ATTACK',
		cost: 2,
		target: 'ENEMY',
		value: 8,
		rarity: 'common',
		effects: [
			{type: 'damage', value: 8, target: 'ENEMY'},
			{type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'exposed'},
		],
	},
	{
		id: 'caocao_harsh_march',
		name: 'Harsh March',
		type: 'ATTACK',
		const 1, 
		target: 'ENEMY',
		value: 7;
		rarity: 'common',
		effects: [
			{type: 'damage', value: 7, target: 'ENEMY'},
			{type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'panic'},
		],
	},
	{
		id: 'caocao_chain_orders',
		name: 'Chain Orders',
		type: 'SKILL',
		cost: 1,
		target: 'SELF',
		value: 5,
		rarity: 'common',
		effects: [
			{type: 'block', value: 5, target: 'SELF'},
			{type: 'apply_status', value: 1, target: 'SELF', statusId: 'command'},
		],
	},
	{
    id: 'caocao_iron_discipline',
    name: 'Iron Discipline',
    type: 'SKILL',
    cost: 1,
    target: 'SELF',
    value: 8,
    rarity: 'common',
    effects: [
      { type: 'block', value: 8, target: 'SELF' },
      { type: 'energy', value: -1, target: 'SELF' },
    ],
	},
	{
		id: 'caocao_requisition',
		name: 'Requisition',
		type: 'SKILL',
		cost: 0,
		target: 'ENEMY',
		rarity: 'common',
		effects: [
			{type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'supply_shortage'},
			{type: 'draw', value: 1, target: 'SELF'},
		],
	},
  {
    id: 'caocao_execution_order',
    name: 'Execution Order',
    type: 'ATTACK',
    cost: 1,
    target: 'ENEMY',
    value: 8,
    rarity: 'common',
    effects: [
      { type: 'damage', value: 8, target: 'ENEMY' },
      { type: 'damage', value: 4, target: 'ENEMY', condition: 'target_has_panic' },
    ],
  },
	{
		id: 'caocao_tax_levy',
		name: 'Tax Levy',
		type: 'SKILL',
		cost: 1,
		target: 'SELF',
		rarity: 'common',
    effects: [
      { type: 'draw', value: 1, target: 'SELF' },
      { type: 'apply_status', value: 1, target: 'SELF', statusId: 'command' },
    ],
	},
	{
		id: 'caocao_logistics_read',
		name: 'Logistics Read',
		type: 'SKILL',
		cost: 1,
		target: 'SELF',
		rarity: 'common',
    effects: [
      { type: 'draw', value: 2, target: 'SELF' },
      { type: 'apply_status', value: 1, target: 'SELF', statusId: 'formation' },
    ],
  },
  {
    id: 'caocao_conscription',
    name: 'Conscription',
    type: 'SKILL',
    cost: 1,
    target: 'SELF',
    rarity: 'common',
    effects: [{ type: 'draw', value: 4, target: 'SELF' }],
    exhaust: true,
  },
  {
    id: 'caocao_precise_strike',
    name: 'Precise Strike',
    type: 'ATTACK',
    cost: 1,
    target: 'ENEMY',
    value: 9,
    rarity: 'common',
    effects: [{ type: 'damage', value: 9, target: 'ENEMY' }],
  },
  {
    id: 'caocao_structure_withdrawal',
    name: 'Structured Withdrawal',
    type: 'SKILL',
    cost: 1,
    target: 'SELF',
    value: 7,
    rarity: 'common',
    effects: [
      { type: 'block', value: 7, target: 'SELF' },
      { type: 'draw', value: 1, target: 'SELF' },
    ],
    retain: true,
  },
	{
		id: 'caocao_forced_labor',
		name: 'Forced Labor',
		type: 'SKILL',
		cost: 0,
		target: 'SELF',
		rarity: 'common',
    effects: [
      { type: 'draw', value: 3, target: 'SELF' },
      { type: 'apply_status', value: 1, target: 'SELF', statusId: 'low_morale' },
    ],
  },
  {
    id: 'caocao_quell_revolt',
    name: 'Quell Revolt',
    type: 'ATTACK',
    cost: 2,
    target: 'ALL_ENEMIES',
    value: 6,
    rarity: 'common',
    effects: [
      { type: 'damage', value: 6, target: 'ALL_ENEMIES' },
      { type: 'apply_status', value: 1, target: 'ALL_ENEMIES', statusId: 'exposed' },
    ],
  },
	{
		id: 'caocao_large_scale_maneuver',
		name: 'Large Scale Maeuver',
		type: 'ATTACK',
		cost: 2,
		target: 'ALL_ENEMIES',
		value: 5,
		rarity: 'common',
    effects: [
      { type: 'damage', value: 5, target: 'ALL_ENEMIES' },
      { type: 'apply_status', value: 1, target: 'ALL_ENEMIES', statusId: 'broken_formation' },
    ],
	},
	{
		id: 'caocao_edict_of_supply',
		name: 'Edict of Supply',
		type: 'SKILL',
		type: 1,
		target: 'SELF',
		rarity: 'common',
    effects: [
      { type: 'block', value: 6, target: 'SELF' },
      { type: 'energy', value: 1, target: 'SELF' },
    ],
    exhaust: true,
  },
	{
		id: 'caocao_silent_threat',
		name: 'Silent Threat',
		type: 'ATTACK',
		cost: 0,
		target: 'ENEMY',
		value: 4,
		rarity: 'common',
    effects: [
      { type: 'damage', value: 4, target: 'ENEMY' },
      { type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'panic' },
    ],
    fleeting: true,
  },
	{
		id: 'caocao_encircle',
		name: 'Encircle',
		type: 'ATTACK',
		cost: 2,
		target: 'ENEMY',
		value: 10,
		rarity: 'common',
    effects: [
      { type: 'damage', value: 10, target: 'ENEMY' },
      { type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'encircled' },
    ],
  },
	{
		id: 'caocao_requistion_orders',
		name: 'Requisition Orders',
		type: 'SKILL',
		cost: 1,
		target: 'SELF',
		rarity: 'common',
    effects: [
      { type: 'draw', value: 2, target: 'SELF' },
      { type: 'energy', value: -1, target: 'SELF' },
    ],
	},
	{
    id: 'caocao_false_surrender',
    name: 'False Surrender',
    type: 'SKILL',
    cost: 1,
    target: 'ENEMY',
    rarity: 'common',
    effects: [
      { type: 'apply_status', value: 2, target: 'ENEMY', statusId: 'panic' },
      { type: 'block', value: 4, target: 'SELF' },
    ],
    exhaust: true,
  },
	{
		id: 'caocao_ordered_shot',
		name: 'Ordered Shot',
		type: 'ATTACK',
		cost: 1,
		target: 'ENEMY',
		value: 6,
		rarity: 'common',
		effects: [
			{type: 'damage', value: 6, target: 'ENEMY'},
			{type: 'apply_status', value: 1, target: 'SELF', statusId: 'command'},
		],
	},
	{
		id: 'caocao_fortress_defense',
		name: 'Fortress Defense',
		type: 'SKILL',
		cost: 2,
		target: 'SELF',
		value: 12,
		rarity: 'common',
    effects: [
      { type: 'block', value: 12, target: 'SELF' },
      { type: 'apply_status', value: 1, target: 'SELF', statusId: 'formation' },
    ],
	},
	{
		id: 'caocao_tax_collection',
		name: 'Tax Collection',
		type: 'SKILL',
		cost: 0,
		target: 'SELF',
		rarity: 'common',
    effects: [
      { type: 'draw', value: 1, target: 'SELF' },
      { type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'supply_shortage' },
    ],
  },
	{
		id: 'caocao_immovable',
		name: 'Immovable',
		type: 'SKILL',
		cost: 1,
		target: 'SELF',
		value: 9, 
		rarity: 'common',
    effects: [
      { type: 'block', value: 9, target: 'SELF' },
      { type: 'energy', value: -1, target: 'SELF' },
    ],
  {
    id: 'caocao_coordinated_strike',
    name: 'Coordinated Strike',
    type: 'ATTACK',
    cost: 1,
    target: 'ENEMY',
    value: 5,
    rarity: 'common',
    effects: [
      { type: 'damage', value: 5, target: 'ENEMY' },
      { type: 'damage', value: 3, target: 'ENEMY', condition: 'player_has_command' },
    ],
  },
	{
		id: 'caocao_cavalry_raid',
		name: 'Cavalry Raid',
		type: 'ATTACK',
		cost: 2,
		target: 'ENEMY',
		value: 14,
		rarity: 'common',
		effects: [{type: 'damage', value: 14, target: 'ENEMY'}],
		exhaust: true,
	},
	{
		id: 'caocao_drill_seargeant',
		name: 'Drill Seargeant',
		type: 'SKILL',
		cost: 2,
		target: 'SELF',
		rarity: 'common',
    effects: [
      { type: 'block', value: 8, target: 'SELF' },
      { type: 'apply_status', value: 2, target: 'SELF', statusId: 'command' },
    ],
  },
  {
	id: 'caocao_intimidation',
	name: 'Intimidation',
	type: 'SKILL',
	cost: 1,
	target: 'ENEMY',
	rarity: 'common',
	effects: [{type: 'apply_status', value: 2, target: 'ENEMY', statusId: 'panic'}
  },
  
  // Uncommon
  {
	id: 'caocao_command_reserve',
	name: 'Command Reserve',
	type: 'SKILL',
	cost: 1,
	target: 'SELF',
	rarity: 'uncommon',
    effects: [{ type: 'apply_status', value: 3, target: 'SELF', statusId: 'command' }],
	exhaust: true,
  },
  {
    id: 'caocao_punitive_raid',
    name: 'Punitive Raid',
    type: 'ATTACK',
    cost: 2,
    target: 'ENEMY',
    value: 11,
    rarity: 'uncommon',
    effects: [
      { type: 'damage', value: 11, target: 'ENEMY' },
      { type: 'apply_status', value: 2, target: 'ENEMY', statusId: 'supply_shortage' },
    ],
  },
  {
	id: 'caocao_administrive_purge',
	name: 'Administrative Purge',
	type: 'ATTACK',
	cost: 2,
	target: 'ALL_ENEMIES',
	value: 5,
	rarity: 'uncommon',
    effects: [
      { type: 'damage', value: 5, target: 'ALL_ENEMIES' },
      { type: 'apply_status', value: 1, target: 'ALL_ENEMIES', statusId: 'panic' },
    ],
  },
  {
    id: 'caocao_seize_stores',
    name: 'Seize Stores',
    type: 'SKILL',
    cost: 1,
    target: 'SELF',
    rarity: 'uncommon',
    effects: [
      { type: 'energy', value: 1, target: 'SELF' },
      { type: 'apply_status', value: 1, target: 'SELF', statusId: 'command' },
    ],
  },
  {
	id: 'caocao_formation_drill',
	name: 'Formation Drill',
	type: 'SKILL',
	cost: 2,
	target: 'SELF',
	value: 11,
	rarity: 'uncommon',
    effects: [
      { type: 'block', value: 11, target: 'SELF' },
      { type: 'apply_status', value: 3, target: 'SELF', statusId: 'formation' },
    ],
  },
  {
    id: 'caocao_blackmail',
    name: 'Blackmail Envoy',
    type: 'ATTACK',
    cost: 1,
    target: 'ENEMY',
    value: 6,
    rarity: 'uncommon',
    effects: [
      { type: 'damage', value: 6, target: 'ENEMY' },
      { type: 'apply_status', value: 2, target: 'ENEMY', statusId: 'panic' },
    ],
  },
  {
	id: 'caocao_structured_withdrawal',
	name: 'Structured Withdrawal',
	type: 'SKILL',
	cost: 1,
	target: 'SELF',
	value: 9,
	rarity: 'uncommon',
    effects: [
      { type: 'block', value: 9, target: 'SELF' },
      { type: 'draw', value: 1, target: 'SELF' },
    ],
	retain: true,
  },
  {
	id: 'caocao_choke_route',
	name: 'Choke_route',
	type: 'ATTACK',
	cost: 2,
	target: 'ENEMY',
	value: 10,
	rarity: 'uncommon',
    effects: [
      { type: 'damage', value: 10, target: 'ENEMY' },
      { type: 'apply_status', value: 2, target: 'ENEMY', statusId: 'broken_formation' },
    ],
  },
  {
	id: 'caocao_central_command',
	name: 'Central Command',
	type: 'POWER',
	cost: 2,
	target: 'SELF',
	rarity: 'uncommon',
    effects: [],
    description: 'Power: At the start of your turn, gain 1 Command.',
  },
  {
	id: 'caocao_silent_court',
	name: 'Silent Court',
	type: 'POWER',
	cost: 2,
	target: 'SELF',
	rarity: 'uncommon',
	effects: [],
    description: 'Power: The first time you apply Panic each turn, draw 1 card.',
  },
  {
	id: 'caocao_quell_uprising',
	name: 'Quell Uprising',
	type: 'ATTACK',
	cost: 2,
	target: 'ALL_ENEMIES',
	value: 7,
	rarity: 'uncommon',
    effects: [
      { type: 'damage', value: 7, target: 'ALL_ENEMIES' },
      { type: 'apply_status', value: 1, target: 'ALL_ENEMIES', statusId: 'exposed' },
    ],
  },
  {
	id: 'caocao_iron_fortification',
	name: 'Iron Fortification',
	type: 'SKILL',
	cost: 2,
	target: 'SELF',
	value: 14,
	rarity: 'uncommon',
    effects: [
      { type: 'block', value: 14, target: 'SELF' },
      { type: 'apply_status', value: 1, target: 'SELF', statusId: 'entrenched' },
    ],
  },
  {
	id: 'caocao_supply_seizure',
	name: 'Supply Seizure',
	type: 'SKILL',
	cost: 1,
	target: 'ENEMY',
	rarity: 'uncommon',
    effects: [
      { type: 'apply_status', value: 2, target: 'ENEMY', statusId: 'supply_shortage' },
      { type: 'draw', value: 1, target: 'SELF' },
    ],
  },
  {
    id: 'caocao_terrifying_wrath',
    name: 'Terrifying Wrath',
    type: 'ATTACK',
    cost: 1,
    target: 'ENEMY',
    value: 7,
    rarity: 'uncommon',
    effects: [
      { type: 'damage', value: 7, target: 'ENEMY' },
      { type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'panic' },
      { type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'low_morale' },
    ],
  },
  {
	id: 'caocao_double_cross',
	name: 'Double Cross',
	type: 'SKILL',
	cost: 1,
	target: 'SELF',
	rarity: 'uncommon',
    effects: [
      { type: 'draw', value: 2, target: 'SELF' },
      { type: 'energy', value: 1, target: 'SELF' },
      { type: 'apply_status', value: 1, target: 'SELF', statusId: 'low_morale' },
    ],
    exhaust: true,
  },
  {
	id: 'caocao_pincer_movement',
	name: 'Pincer Movement',
	type: 'ATTACK',
	cost: 2,
	target: 'ENEMY',
	value: 7,
	rarity: 'uncommon',
    effects: [
      { type: 'damage', value: 7, target: 'ENEMY' },
      { type: 'damage', value: 7, target: 'ENEMY' },
    ],
  },
  {
	id: 'caocao_fortify_command',
	name: 'Fortify Command',
	type: 'SKILL',
	cost: 2,
	target: 'SELF',
    effects: [
      { type: 'block', value: 8, target: 'SELF' },
      { type: 'apply_status', value: 2, target: 'SELF', statusId: 'command' },
      { type: 'apply_status', value: 1, target: 'SELF', statusId: 'formation' },
    ],
  },
  {
	id: 'caocao_moment_of_weakness',
	name: 'Moment Of Weakness',
	type: 'ATTACK',
	cost: 1,
	target: 'ENEMY',
	value: 5,
	rarity: 'uncommon',
    effects: [
      { type: 'damage', value: 5, target: 'ENEMY' },
      { type: 'apply_status', value: 2, target: 'ENEMY', statusId: 'exposed' },
    ],
  },
  {
	id: 'caocao_ruthless_tactics',
	name: 'Ruthless Tactics',
	type: 'SKILL',
	cost: 0,
	target: 'SELF',
	rarity: 'uncommon',
    effects: [
      { type: 'draw', value: 3, target: 'SELF' },
      { type: 'apply_status', value: 2, target: 'SELF', statusId: 'low_morale' },
    ],
  },
  {
	id: 'caocao_total_war',
	name: 'Total War',
	type: ' ATTACK',
	cost: 3,
	target: 'ALL_ENEMIES',
	value: 8,
	rarity: 'uncommon',
    effects: [
      { type: 'damage', value: 8, target: 'ALL_ENEMIES' },
      { type: 'apply_status', value: 1, target: 'ALL_ENEMIES', statusId: 'panic' },
    ],
  },
  {
	id: 'caocao_secret_edict',
	name: 'Secret Edict',
	type: 'SKILL',
	cost: 1,
	target: 'SELF',
	rarity: 'uncommon',
    effects: [
      { type: 'apply_status', value: 2, target: 'SELF', statusId: 'command' },
      { type: 'draw', value: 2, target: 'SELF' },
    ],
    exhaust: true,
  },
  {
	id: 'caocao_iron_wall_power',
	name: 'Iron Wall Power',
	type: 'POWER',
	cost: 2,
	target: 'SELF',
	rarity: 'uncommon',
    effects: [
      { type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'supply_shortage' },
      { type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'broken_formation' },
    ],
  },
  {
    id: 'caocao_undermine',
    name: 'Undermine',
    type: 'SKILL',
    cost: 1,
    target: 'ENEMY',
    rarity: 'uncommon',
    effects: [
      { type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'supply_shortage' },
      { type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'broken_formation' },
    ],
  },
  {
	id: 'caocao_concentrated_fire',
	name: 'Concentrated Fire';
	type: 'ATTACK',
	cost: 2,
	target: 'ENEMY',
	value: 15,
	rarity: 'uncommon',
	effects: [{type: 'damage', value: 15, target: 'ENEMY'}],
	exhaust: true,
  }
  {
	id: 'caocao_tactical_genius',
	name: 'Tactica Genius',
	type: 'SKILL',
	cost: 1,
	target: 'SELF',
	rarity: 'uncommon',
    effects: [
      { type: 'energy', value: 1, target: 'SELF' },
      { type: 'draw', value: 1, target: 'SELF' },
      { type: 'apply_status', value: 1, target: 'SELF', statusId: 'command' },
    ],
  }
  {
	id: 'caocao_subjugate',
	name: 'Subjugate',
	type: 'ATTACK',
	cost: 2,
	target: 'ENEMY',
	value: 9,
	rarity: 'uncommon',
    effects: [
      { type: 'damage', value: 9, target: 'ENEMY' },
      { type: 'apply_status', value: 2, target: 'ENEMY', statusId: 'panic' },
      { type: 'apply_status', value: 1, target: 'ENEMY', statusId: 'supply_shortage' },
    ],
  },
  {
	id: 'caocao_call_reserves',
	name: 'Call Reserves',
	type: 'SKILL',
	cost: 0,
	target: 'SELF',
	rarity: 'uncommon',
    effects: [
      { type: 'draw', value: 3, target: 'SELF' },
      { type: 'apply_status', value: 1, target: 'SELF', statusId: 'command' },
    ],
    exhaust: true,
  },
];
