import type { Combatant, Enemy, Status, StatusId } from '../types';
import type { EffectQueue } from './EffectQueue';

export type StatusTrigger = 'ownerTurnStart' | 'ownerTurnEnd';

interface StatusDefinition {
  name: string;
  description: string;
  defaultDuration?: number | null;
  tickOn?: StatusTrigger;
  stackDecayOnTick?: number;
  damagePerStack?: number;
  flatDamagePerStack?: number;
  expiresOn?: StatusTrigger;
}

const STATUS_DEFINITIONS: Record<StatusId, StatusDefinition> = {
  valor: {
    name: 'Valor',
    description: '+2 attack damage per stack this turn',
    defaultDuration: 1,
    expiresOn: 'ownerTurnEnd',
  },
  formation: {
    name: 'Formation',
    description: '+1 block gained per stack this turn',
    defaultDuration: 1,
    expiresOn: 'ownerTurnEnd',
  },
  exposed: {
    name: 'Exposed',
    description: 'Take 50% more damage this turn',
    defaultDuration: 1,
    expiresOn: 'ownerTurnEnd',
  },
  disarmed: {
    name: 'Disarmed',
    description: 'Deal 25% less attack damage this turn',
    defaultDuration: 1,
    expiresOn: 'ownerTurnEnd',
  },
  burning: {
    name: 'Burning',
    description: 'Take damage equal to stacks, then lose 1 stack',
    tickOn: 'ownerTurnEnd',
    damagePerStack: 1,
    stackDecayOnTick: 1,
  },
  bleed: {
    name: 'Bleed',
    description: 'Take half stacks damage at end of turn, then lose 1 stack',
    tickOn: 'ownerTurnEnd',
    flatDamagePerStack: 0,
    stackDecayOnTick: 1,
  },
  broken_formation: {
    name: 'Broken Formation',
    description: 'Block gained is halved this turn',
    defaultDuration: 1,
    expiresOn: 'ownerTurnEnd',
  },
  entrenched: {
    name: 'Entrenched',
    description: 'Retain 50% of block between turns',
    defaultDuration: null,
  },
  momentum: {
    name: 'Momentum',
    description: 'Stored attack bonus consumed on the next attack',
    defaultDuration: null,
  },
  command: {
    name: 'Command',
    description: 'Strategic resource generated by cards and powers',
    defaultDuration: null,
  },
  fire_setup: {
    name: 'Fire Setup',
    description: 'Your next Burning effect is amplified',
    defaultDuration: null,
  },
  panic: {
    name: 'Panic',
    description: 'First card each turn costs 1 more energy',
    defaultDuration: null,
  },
  supply_shortage: {
    name: 'Supply Shortage',
    description: 'Cannot gain Momentum or Command',
    defaultDuration: 2,
    expiresOn: 'ownerTurnEnd',
  },
  isolated: {
    name: 'Isolated',
    description: 'Takes bonus damage from single-target attacks',
    defaultDuration: 2,
    expiresOn: 'ownerTurnEnd',
  },
  insight: {
    name: 'Insight',
    description: 'Future deck manipulation support', //Probably with zhuge liang when he gets introduced
    defaultDuration: 1,
    expiresOn: 'ownerTurnEnd',
  },
  guarded: {
    name: 'Guarded',
    description: 'Negates the next debuff',
    defaultDuration: null,
  },
	revealed: {
		name: 'Revealed',
		description: 'True target exposed; illusions no longer conceal it',
		defaultDuration: null,
	},
	evade: {
		name: 'Evade',
		description: 'Negates one incoming hit per stack',
		defaultDuration: null,
	},
  starving: {
    name: 'Starving',
    description: '-1 Energy next turn',
    defaultDuration: 1,
    expiresOn: 'ownerTurnStart',
  },
	low_morale: {
		name: 'Low Morale',
		description: 'Deal 25%  less attack damage this turn',
		defaultDuration: 1,
		expiresOn: 'ownerTurnEnd',
	},
  fire: {
    name: 'Fire',
    description: 'Take 3 damage per stack, then lose 1 stack',
    tickOn: 'ownerTurnEnd',
    flatDamagePerStack: 3,
    stackDecayOnTick: 1,
  },
	encircled: {
		name: 'Encircled',
		description: 'Cannot gain block',
		defaultDuration: null,
	},
	rallied: {
		name: 'Rallied',
		description: 'Gain +2 attack damage and +2 block this turn',
		defaultDuration: 1,
		expiresOn: 'ownerTurnEnd',
	},
	frost: {
		name: 'Frost',
		description: '-1 Energy next turn',
		defaultDuration: 1,
		expiresOn: 'ownerTurnStart',
	},
	poison: {
		name: 'Poison',
		description: 'Take damage equal to stacks, then lose 1 stack',
		tickOn: 'ownerTurnEnd',
		damagePerStack: 1,
		stackDecayOnTick: 1,
	},
	strength: {
		name: 'Strength',
		description: '+2 damage per stack',
		defaultDuration: null,
	},
	weak: {
		name: 'Weak',
		description: 'Deal 25% less damage this turn',
		defaultDuration: 1,
		expiresOn: 'ownerTurnEnd',
	},
	vulnerable: {
		name: 'Vulnerable',
		description: 'Take 50% more damage this turn',
		defaultDuration: 1,
		expiresOn: 'ownerTurnEnd',
	},
};

export function createStatus(id: StatusId, stacks: number): Status {
  const definition = STATUS_DEFINITIONS[id];
  return {
    id,
    name: definition.name,
    description: definition.description,
    stacks: Math.max(1, stacks),
    duration: definition.defaultDuration ?? undefined,
  };
}

export function getStatusDefinition(id: StatusId): StatusDefinition {
	return STATUS_DEFINITIONS[id];
}

export function processStatusTrigger(
  target: Combatant | Enemy,
  trigger: StatusTrigger,
  effectQueue: EffectQueue,
  context: { source: 'player' | 'enemy'; sourceEnemyIndex?: number }
): void {
  for (const status of target.statuses) {
    const definition = STATUS_DEFINITIONS[status.id];
    if (definition.tickOn !== trigger) {
      continue;
    }

    let damage = 0;
    if (definition.damagePerStack) {
      damage += definition.damagePerStack * status.stacks;
    }
    if (definition.flatDamagePerStack) {
      damage += definition.flatDamagePerStack * status.stacks;
    }
    if (status.id === 'bleed') {
      damage = Math.max(1, Math.ceil(status.stacks / 2));
    }

		if (damage > 0) {
			effectQueue.enqueue(
				{
					type: 'damage',
					value: damage,
					target: 'SELF',
				},
				context
			);
		}

		if (definition.stackDecayOnTick) {
			status.stacks = Math.max(0, status.stacks - definition.stackDecayOnTick);
		}
	}

  cleanupExpiredStatuses(target, trigger);
}

export function cleanupExpiredStatuses(target: Combatant | Enemy, trigger: StatusTrigger): void {
  target.statuses = target.statuses
    .map((status) => {
      const definition = STATUS_DEFINITIONS[status.id];
      const nextStatus = { ...status };

			if (definition.expiresOn === trigger && nextStatus.duration !== null && nextStatus.duration !== undefined) {
				nextStatus.duration = Math.max(0, nextStatus.duration - 1);
			}

			return nextStatus;
    })
    .filter((status) => status.stacks > 0 && (status.duration === undefined || status.duration === null || status.duration > 0));
}

export function removeStatus(target: Combatant | Enemy, statusId): void {
	target.statuses = target.statuses.filter((status) => status.id !== statusId);
}